totalbill = input("What was the total bill? ")
totalbill_int = int(totalbill)
tip = input("What percentage tip would you like to give? 10, 12, or 15? ")
tip_int = int(tip)
people = input("How many people to split the bill? ")
people_int = int(people)
new_tip_int = ((tip_int / 100) * totalbill_int)
eachperson_shouldpay = ((totalbill_int + new_tip_int) / people_int)
# new_eachperson_shouldpay = print(round(eachperson_shouldpay,2))
final_amount = "{:.2f}".format(eachperson_shouldpay)
print(f"Each person should pay: ${final_amount}")
